name: K6 Performance Tests

on:
  push:
  pull_request:

jobs:
  k6-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: playwright

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
          sudo apt-get install k6

      - name: Run k6 smoke test
        run: k6 run performance/smoke.test.js
