name: K6 Performance Tests

on:
  push:
  pull_request:

jobs:
  k6-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: performance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates gnupg curl
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
          k6 version

      - name: Install dependencies (with ci fallback)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then npm ci || npm install; else npm install; fi

      - name: Run k6 smoke test
        run: k6 run smoke.test.js
