name: Percy Visual Tests (Playwright)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'playwright/**'
      - 'scripts/percy-snapshots.ts'
      - '.github/workflows/playwright-percy.yml'

jobs:
  percy-visual-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: playwright

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm install @percy/cli
          npm install @percy/playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Percy visual test run
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npm run percy:playwright
