name: Percy Visual Tests (Cypress)

on:
  push:
  pull_request:

jobs:
  percy-cypress:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cypress

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (with ci fallback)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then npm ci || npm install; else npm install; fi
          npm install @percy/cli
          npm install @percy/cypress

      - name: Generate synthetic users fixtures
        if: always()
        working-directory: .
        shell: bash
        run: |
          if [ -f package-lock.json ]; then npm ci || npm install; else npm install; fi
          npm run data:users -- --count=20 --seed=${{ github.run_number }}

      - name: Run Cypress tests with Percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx percy exec -- npx cypress run
