name: Playwright Tests

on:
  push:
  pull_request:

jobs:
  playwright-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: playwright

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with Allure
        run: npx playwright test --reporter=list,allure-playwright

      - name: Generate Allure HTML report
        run: npx allure generate playwright/allure-results --clean -o playwright/allure-report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-allure-report
          path: playwright/allure-report
